### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by julianofischer** [perone/django-gis-brasil#16]
Pessoal,
o erro abaixo acontece quando eu digito o seguinte comando:

python manage.py gisloader --municipios-brasil

Estou usando postgis e executei syncdb sem problemas.

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 238, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 217, in create_parser
    usage=self.usage(subcommand),
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 206, in usage
    return '%s\n\n%s' % (usage, self.help)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 36: ordinal not in range(128)

**Comment by perone** [comment]
Oi Juliano, obrigado pelo report, qual versão do Django você está usando ? E qual versão do PostgreSQL e também do PostGIS ? Valeu !

**Comment by gwainer** [comment]
Juliano, se você puder veja também qual o encoding utilizado no banco.

**Comment by julianofischer** [comment]
Django 1.6
Postgres 9.1
Postgis 2.0.3

Digitei \encoding no psql e apareceu UTF-8

Abraços

**Comment by perone** [comment]
@julianofischer valeu pelo resposta, você está usando a versão de desenvolvimento (v.0.4) do django-gis-brasil ou a versão de release (v.0.3) ? Obrigado !

**Comment by julianofischer** [comment]
Baixei a versão do pip.

**Comment by perone** [comment]
Acho que este problema já foi corrigido em desenvolvimento, você consegue instalar o django-gis-brasil de dev usando:

```
pip uninstall django-gis-brasil
pip install https://github.com/perone/django-gis-brasil/archive/master.zip
```

Você precisará remover o DB e criar de novo ou apagar as tabelas antes de rodar o `python manage.py syncdb`. Valeu !

**Comment by julianofischer** [comment]
Perone,
com a versão em desenvolvimento funcionou.

Vamos por a mão na massa agora!

**Comment by perone** [comment]
Beleza, valeu pelo report @julianofischer !
