### ISSUE TITLE
Encode error when importing data with manage.py gisloader

### ISSUE THREAD

**Issue by luzfcb** [perone/django-gis-brasil#5]
Ola, estou tentando utilizar o django-gis-brasil e estou recebendo este erro ao tentar importar os dados:

``` bash
(venv)oficina@sutransdev2:~/PycharmProjects/projeto_sgt/sgt$ python manage.py gisloader
django-gisbrasil v.0.2
Authors: CodeFish Team (Christian S. Perone, Leandro Nunes, Gabriel Wainer)

Loading Brazilian cities data into Database (this may take a while)...DjangoUnicodeDecodeError: 'utf8' codec can't decode byte 0xe3 in position 4: unexpected end of data. You passed in 'Regi\xe3o' (<type 'str'>)
```

Estou utilizando o Ubuntu 12.04 x64, Django 1.5.4, Postgres 9.1, Postgis 2.0.2.

Verifiquei que a definição de encode dos arquivos estão definidos como:

``` bash
# happy fish-coding: utf-8
```

tentei substituir a str de encode nos arquivos por:

``` python
# -*- coding: utf-8 -*-
```

Mas não funcionou.
Alguma sugestão?

**Comment by perone** [comment]
Oi Fábio, obrigado pelo relato detalhado do problema. Vamos ver o que pode ser, o encoding do arquivo não é o problema pois o interpretador procura por uma regex utilizando "coding: [encoding]" na primeira linha do arquivo de fonte, portanto tanto faz o que está escrito antes do "coding" no momento de definir o encoding.

**Comment by luzfcb** [comment]
Acho que o problema é no Elementary OS Luna (que é baseado no Ubuntu 12.04), a distribuição linux que utilizo no trabalho.
Fiz uma instalação limpa com o ubuntu 13.04 em casa, e importou corretamente. Queria descobri que raio de modificação eles fizeram no Luna que aparece esse erro.

**Comment by perone** [comment]
Vou remover os acentos na issue #6 para não termos mais estes problemas.
